### ISSUE TITLE
some errers!

### ISSUE THREAD

**Issue by xiaoshuguo750** [DT42/squeezenet_demo#11]
Hi!
How can I solve the problem?

from simdat.core import dp_tools
ImportError: No module named 'simdat'

Thank you!

**Comment by cvtower** [comment]
seems like the simdat is private lib of the auther: https://github.com/tammyyang/simdat.

**Comment by muthiyanbhushan** [comment]
I get below error when I add Simdat to the PYTHONPATH.

/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "squeezenet_demo.py", line 14, in <module>
    from simdat.core import dp_tools
  File "/squeezenet_demo/simdat/core/dp_tools.py", line 8, in <module>
    from simdat.core import image
  File "/squeezenet_demo/simdat/core/image.py", line 8, in <module>
    from simdat.core.so import math_tools
ImportError: ~/simdat/core/so/math_tools.so: undefined symbol: _Py_ZeroStruct

Can someone let me know what might cause this error.

Thanks.

**Comment by tammyyang** [comment]
Hi, 

Yes, the simdat package is my private lib. I do have plan to replace it to make it easier to run the demo script, but unfortunately, I do not think I have time for this task in the coming month. 

What simdat do is very simple, it prepares the training data and testing data sets required by the mode. If the issue is urgent to you, you may also replace the data generation process (such as dp.train_data_generator in line 109) to any process which can help prepare the data generator.

The timeline to replace dp_tools to make squeezenet_demo survive without any external dependency will be early July.

**Comment by HaFred** [comment]
> Hi,
> 
> Yes, the simdat package is my private lib. I do have plan to replace it to make it easier to run the demo script, but unfortunately, I do not think I have time for this task in the coming month.
> 
> What simdat do is very simple, it prepares the training data and testing data sets required by the mode. If the issue is urgent to you, you may also replace the data generation process (such as dp.train_data_generator in line 109) to any process which can help prepare the data generator.
> 
> The timeline to replace dp_tools to make squeezenet_demo survive without any external dependency will be early July.

Hi @tammyyang , wonder how it goes now? The simdat is still a must to run the demo?
